version: "3"

services:
  node-server:
    tty: true
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    ports:
      - 3200:3200
    restart: unless-stopped
    volumes:
      - ./:/app
